version: '3.9'

services:
  db:
    image: postgres
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=web
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
  web:
    build: .
    # Start test server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_volume: