version: '3.9'

services:
  db:
    image: postgres
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  web:
    build: .
    # start gunicorn server
    command: gunicorn employees.wsgi:application --bind 0.0.0.0:8000
    # открыть порт 8000 наружу
    expose:
       - 8000
    # Подключаем статические и медиа файлы
    volumes:
      #- .:/home/app/web
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

    env_file:
      - ./.env.prod
    # Дожидаемся запуска контейнера db
    depends_on:
      - db

  nginx:
    build: ./nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: