# Generated by Django 3.1.6 on 2021-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='man',
            name='record_creation_date',
        ),
        migrations.RemoveField(
            model_name='man',
            name='reg_number',
        ),
        migrations.AddField(
            model_name='man',
            name='Department',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='man',
            name='dismissal_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='man',
            name='employment_start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='man',
            name='position',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
