# Generated by Django 3.1.6 on 2021-09-07 19:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210907_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.RemoveField(
            model_name='people',
            name='dismissal_date',
        ),
        migrations.RemoveField(
            model_name='people',
            name='employment_start_date',
        ),
        migrations.AddField(
            model_name='people',
            name='end_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AddField(
            model_name='people',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Department_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Oтдел'),
        ),
        migrations.AlterField(
            model_name='people',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='people',
            name='department',
            field=models.CharField(default=None, max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.CharField(default=None, max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='people',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
