# Generated by Django 3.1.6 on 2021-09-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210907_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departments'),
        ),
    ]
