# Generated by Django 3.1.6 on 2021-09-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210907_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания работы'),
        ),
    ]
