# Generated by Django 3.1.6 on 2021-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210908_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
