# Generated by Django 3.1.6 on 2021-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210909_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
